import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
    return (
        <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
            <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
            <p style={{ fontSize: "18px", marginBottom: "30px" }}>
                This project was generated By{" "}
                <a href="" style={{ color: "#87CEFA", textDecoration: "none" }}>
                    Revier
                </a>
                Quickly use below links to navigate through all pages.
            </p>
            <ul style={{ liststyle: "none", padding: "0" }}>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/serendaleai" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Serendaleai
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/chatgpt" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        ChatGPT
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/mainui" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        MainUI
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/startscreens" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        StartScreens
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/dashboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Dashboard
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/withdraw" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        WithDraw
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/cryptocaplanding" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        CryptoCapLanding
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/landingOne" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        LandingOne
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/landingtwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        LandingTwo
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/rightbanner" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        RightBanner
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/nftmarketplace" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        NFTMarketplace
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/deposits" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Deposits
                    </Link>
                </li>
            </ul>
        </div>
    );
};

export default Home;